openapi: 3.0.0
info:
  title: ToDos
  version: 1.0.0
servers:
  - url: http://{{host}}{{path}}
paths:
  /todos:
    post:
      tags:
        - todos
      summary: create
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                title: Sample ToDo
                description: This is a sample ToDo description
                dueDate: '2024-08-31T00:00:00.000Z'
                priority: medium
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
